# this will create a calk elf

calk_elf: calc_main.o calc_sum.o
	@sleep 2
	@gcc calc_main.o calc_sum.o  -o calk

calc_main.o: calc_main.c
	@sleep 2
	@gcc -c calc_main.c -o calc_main.o

calc_sum.o: calc_sum.c
	@sleep 2
	@gcc -c calc_sum.c -o calc_sum.o
